
export const topicTags = [
    "Merge Sort",
    "Reservoir Sampling",
    "String",
    "Math",
    "Segment Tree",
    "Design",
    "Game Theory",
    "Hash Table",
    "Backtracking",
    "Matrix",
    "Minimum Spanning Tree",
    "Rolling Hash",
    "Interactive",
    "Tree",
    "Line Sweep",
    "Suffix Array",
    "Combinatorics",
    "Trie",
    "Eulerian Circuit",
    "Ordered Set",
    "Binary Search Tree",
    "Probability and Statistics",
    "Recursion",
    "Stack",
    "Linked List",
    "Binary Indexed Tree",
    "Graph",
    "Randomized",
    "Brainteaser",
    "Breadth-First Search",
    "Union Find",
    "Counting",
    "Quickselect",
    "Bitmask",
    "Two Pointers",
    "Heap (Priority Queue)",
    "Doubly-Linked List",
    "Rejection Sampling",
    "Biconnected Component",
    "Monotonic Queue",
    "Strongly Connected Component",
    "Dynamic Programming",
    "Bit Manipulation",
    "Divide and Conquer",
    "Sliding Window",
    "Topological Sort",
    "Iterator",
    "Hash Function",
    "Bucket Sort",
    "Greedy",
    "Queue",
    "Shortest Path",
    "Data Stream",
    "Enumeration",
    "Depth-First Search",
    "Binary Tree",
    "String Matching",
    "Prefix Sum",
    "Binary Search",
    "Sorting",
    "Array",
    "Geometry",
    "Radix Sort",
    "Simulation",
    "Counting Sort",
    "Monotonic Stack",
    "Memoization",
    "Number Theory",
    "Database",
    "Shell"
];

